version: "3.8"
services:
  ## server
  backend:
    container_name: "dan100-backend"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=5000
    working_dir: /app

  ## database
  db:
    container_name: dan100-db
    image: mongo
