version: "3.8"
services:
  backend:
    container_name: dan100-backend-dev
    build:
      args:
        NODE_ENV: development
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
