services:
  app:
    container_name: app-prod
    ports:
      - "80:${PORT}"
    command: npm start
    restart: always
    env_file:
      - .env.prod
  mongo:
    container_name: mongo-prod
    restart: always
