name: dockerized-node

services:
  ## server
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
    working_dir: /app
    restart: always
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - mongo

  ## database
  mongo:
    image: mongo
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  ## cache
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongo-data:
